unisoncomputing/share-ui

README.md

The CI image was pointing at the wrong repository.

Update README with correct CI image

---

package-lock.json
package.json
src/metrics.js
src/unisonShare.js

Accidentally removed this. Turning back on.

Re-enable metrics

---

elm-git.json

Latest UI core includes a fix for the gap between icon and title on workspace items.

Update UI Core to include workspace item gap fix

---

netlify.toml

Indent toml

---

netlify.toml
netlify/edge-functions/social-image.tsx

Forcing static redirects

---

netlify/edge-functions/replace-social-content.ts
netlify/edge-functions/social-image.tsx
src/unisonShare.ejs

Enable replace social content

---

netlify/edge-functions/common/share-route.ts
netlify/edge-functions/replace-social-content.ts
netlify/edge-functions/social-image.tsx
package-lock.json
package.json

Use sums up for edge function routing

---

netlify/edge-functions/common/share-route.ts
netlify/edge-functions/replace-social-content.ts
netlify/edge-functions/social-image-helpers/project-branches-social-image.tsx
netlify/edge-functions/social-image-helpers/project-releases-social-image.tsx
netlify/edge-functions/social-image.tsx

SocialImage: add releases and branches

---

elm-git.json
src/UnisonShare/DefinitionDiff.elm
tests/UnisonShare/DefinitionDiffTests.elm

This adds a new API integration for decoding definition diffs.

Definition Diff API integration

---

elm-git.json
src/UnisonShare/Api.elm
src/UnisonShare/DefinitionDiff.elm
src/UnisonShare/DefinitionDiffKey.elm
src/UnisonShare/DefinitionDiffs.elm
src/UnisonShare/InteractiveDoc.elm
src/UnisonShare/Page/ProjectContributionChangesPage.elm

Clicking on the `Update` diffline will fetch a definition diff and render it below.

Render definition diff on click of diffline

---

elm-git.json

Update with new syntax help

---

src/UnisonShare/Api.elm
src/UnisonShare/Page/ProjectContributionChangesPage.elm

Uses the new contribution diff API

Use new contribution diff api

---

elm-git.json
review/suppressed/NoUnused.Modules.json
src/UnisonShare/Api.elm
src/UnisonShare/App.elm
src/UnisonShare/OmniSearch.elm
src/UnisonShare/Page/CatalogPage.elm
src/UnisonShare/Page/ProjectPage.elm
src/css/unison-share/omni-search.css
src/css/unison-share/page/catalog-page.css
webpack.prod.js

Enable omni search on the catalog page, remove the old catalog search, and connect to a new imagined search API.

Enable omni search

---

src/UnisonShare/Api.elm
src/UnisonShare/Contribution.elm
src/UnisonShare/Contribution/ContributionMergeability.elm
src/UnisonShare/Page/ProjectContributionChangesPage.elm
src/UnisonShare/Page/ProjectContributionOverviewPage.elm
src/UnisonShare/Page/ProjectContributionPage.elm
src/UnisonShare/Page/ProjectContributionsPage.elm
src/UnisonShare/ProjectContributionFormModal.elm
src/css/unison-share/page/project-contribution-overview-page.css

Update the merge button to be for merging (instead of "mark as merged"), incorporating a merge-ability check and general status update indication.
Depends on https://github.com/unisoncomputing/share-api/pull/21

Contributions: Add a merge button

---

api-stubs/branch-diff.json
api-stubs/definition-type-diff.json
src/UnisonShare/BranchDiff.elm
src/UnisonShare/BranchDiff/ChangeLine.elm
src/UnisonShare/BranchDiff/ChangeLineId.elm
src/UnisonShare/Page/ProjectContributionChangesPage.elm
webpack.dev.js

To support lib dependency diffs and improve diffing in general, the diff API changed slightly with a new nested node.
Depends on https://github.com/unisoncomputing/share-api/pull/37

Support new diff json schema

---

package-lock.json
package.json
src/unisonShare.js

More holistic upgrade of Sentry to fix https://github.com/unisoncomputing/share-ui/pull/52

Upgrade Sentry

---

src/UnisonShare/App.elm
src/UnisonShare/Link.elm
src/UnisonShare/Page/NotificationsPage.elm
src/UnisonShare/Route.elm

Add the main page infrastructure for the new notifications feature.

Add NotificationsPage skeleton

---

src/UnisonShare/Api.elm

We don't need an email on orgs

Remove email field on org creation

---

elm-git.json
src/UnisonShare/Notification.elm
src/UnisonShare/Page/NotificationsPage.elm
src/UnisonShare/Page/ProjectOverviewPage.elm
src/UnisonShare/Page/ProjectPageHeader.elm
src/UnisonShare/Project/ProjectListing.elm
src/css/unison-share/page.css
src/css/unison-share/page/notifications-page.css

Add initial rendering of the notifications table

---

elm-git.json
review/suppressed/NoUnused.Modules.json
src/UnisonShare/App.elm
src/UnisonShare/Page/NotificationsPage.elm
src/css/unison-share/page/notifications-page.css
tests/e2e/NewOrgModal.spec.ts

Add notification selection controls

---

src/UnisonShare/Page/ProjectContributionChangesPage.elm
src/UnisonShare/Page/ProjectContributionOverviewPage.elm

Removes the notice to fully release the diff feature.

Remove contribution changes beta notice

---

elm-git.json
review/suppressed/NoUnused.Modules.json
src/UnisonShare/Api.elm
src/UnisonShare/App.elm
src/UnisonShare/ErrorCard.elm
src/UnisonShare/NewOrgModal.elm
src/UnisonShare/Notification.elm
src/UnisonShare/OmniSearch.elm
src/UnisonShare/Org.elm
src/UnisonShare/Page/ErrorPage.elm
src/UnisonShare/Page/NotificationsPage.elm
src/UnisonShare/Page/OrgPage.elm
src/UnisonShare/Page/OrgProfilePage.elm
src/UnisonShare/Page/ProfilePage.elm
src/UnisonShare/Page/ProjectContributionChangesPage.elm
src/UnisonShare/Page/ProjectContributionOverviewPage.elm
src/css/unison-share/omni-search.css
src/css/unison-share/page/notifications-page.css
src/css/unison-share/welcome-tour-modal.css
tests/e2e/NotificationsPage.spec.ts
tests/e2e/ProjectContributionChangesPage.spec.ts
tests/e2e/ProjectContributionOverviewPage.spec.ts
tests/e2e/TestHelpers/Api.ts
tests/e2e/TestHelpers/Data.ts
tests/e2e/TestHelpers/Page.ts

Update various decodes on various pages to support new, consistent, shapes of User, Org, and Account.
This depends on https://github.com/unisoncomputing/share-api/pull/70

Update User/Org/Account JSON decoders

---

src/UnisonShare/Api.elm
src/UnisonShare/Page/ProjectContributionsPage.elm

Contributions status fix

---

src/UnisonShare/Notification.elm
src/UnisonShare/Page/NotificationsPage.elm
tests/e2e/NotificationsPage.spec.ts
tests/e2e/TestHelpers/Api.ts
tests/e2e/TestHelpers/Data.ts

Update the notifications decoders to match the API and also better handling of failure.

Update notifications decoding

---

.gitignore
src/UnisonShare/Link.elm
src/UnisonShare/Page/ProjectBranchesPage.elm
src/UnisonShare/Page/ProjectPage.elm
src/UnisonShare/Route.elm
src/UnisonShare/SwitchBranch.elm
tests/UnisonShare/RouteTests.elm

The project branches page doesn't currently utilize pagination.
Add pagination.

Add pagination to the project branches page

---

elm-git.json
src/UnisonShare/Api.elm

Update ui-core which includes the `Dependents` and `Dependencies` variants on the `CodebaseApi.CodebaseEndpoint` sum type and interpret them in `Share.Api`

Add support for new dependents/dependencies apis
